CPC_Schemes: {
  # Dict of CPC Symbols relating to Artificial Intelligence
  'Machine Learning': ['G06N20/00', 'G06N20/10', 'G06N20/20'],
  'Supervised Learning': ['G06N3/09'],
  'Unsupervised Learning': ['G06N3/088'],
  'Reinforcement Learning': ['G06N3/092'],
  'Deep Learning': ['G06N3/08'],
  }
NACE_INDSUTRIES_LV_1: {
    # List of NACE industries, slightly altered to fit keyword search
    'A': ['AGRICULTURE', 'FORESTRY', 'FISHING'],
    'B': ['MINING', 'QUARRYING'],
    'C': ['MANUFACTURING'],
    'D': ['ELECTRICITY', 'GAS', 'STEAM', 'AIR CONDITIONING SUPPLY'],
    'E': ['WATER SUPPLY', 'SEWERAGE', 'WASTE MANAGEMENT', 'REMEDIATION ACTIVITIES'],
    'F': ['CONSTRUCTION'],
    'G': ['WHOLESALE', 'RETAIL', 'REPAIR OF MOTOR VEHICLES AND MOTORCYCLES'],
    'H': ['TRANSPORTATION', 'STORAGE'],
    'I': ['ACCOMMODATION', 'FOOD SERVICE ACTIVITIES'],
    'J': ['INFORMATION', 'COMMUNICATION'],
    'K': ['FINANCIAL ACTIVITIES', 'INSURANCE ACTIVITIES'],
    'L': ['REAL ESTATE'],
    'M': ['PROFESSIONAL ACTIVITIES', 'SCIENTIFIC ACTIVITIES', 'TECHNICAL ACTIVITIES'],
    'N': ['ADMINISTRATIVE ACTIVITIES', 'SUPPORT SERVICE ACTIVITIES'],
    'O': ['PUBLIC ADMINISTRATION', 'DEFENCE', 'COMPULSORY SOCIAL SECURITY'],
    'P': ['EDUCATION'],
    'Q': ['HUMAN HEALTH', 'SOCIAL WORK ACTIVITIES'],
    'R': ['ARTS', 'ENTERTAINMENT', 'RECREATION'],
    'S': ['OTHER SERVICE ACTIVITIES'],
    'T': ['ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS', 'UNDIFFERENTIATED GOODS', 'SERVICES PRODUCING ACTIVITIES OF HOUSEHOLDS FOR OWN USE'],
    'U': ['ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS', 'ACTIVITIES OF EXTRATERRITORIAL BODIES']
    }
# from https://register.epo.org/help?lng=en&topic=countrycodes
EU_COUNTRY_CODES: {
  "EP": "European Patent Office",
  "AT": "Austria",
  "BE": "Belgium",
  "BG": "Bulgaria",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DK": "Denmark",
  "EE": "Estonia",
  "EL": "Greece",
  "ES": "Spain",
  "FI": "Finland",
  "FR": "France",
  "HR": "Croatia",
  "HU": "Hungary",
  "IE": "Ireland",
  "IT": "Italy",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "MT": "Malta",
  "NL": "Netherlands",
  "PL": "Poland",
  "PT": "Portugal",
  "RO": "Romania",
  "SE": "Sweden",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "UK": "United Kingdom"
  }
# Paths
paths: {
  retrieved_data_content: "data/ops_search_response_content.json",
  nace_codes_csv: "data/NACE_CODES.csv"
}